### ISSUE TITLE
UnhandledException

### ISSUE THREAD

**Issue by M9GLiquid** [xxyy/commandblockerultimate#18] opened 2016-04-10 13:29 UTC
10.04 09:26:42 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin CommandBlockerUltimate v1.3.2 generated an exception while executing task 393
10.04 09:26:42 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
10.04 09:26:42 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
10.04 09:26:42 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
10.04 09:26:42 [Server] INFO at java.lang.Thread.run(Thread.java:745)
10.04 09:26:42 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
10.04 09:26:42 [Server] INFO at io.github.xxyy.cmdblocker.lib.com.mcstats.Metrics.postPlugin(Metrics.java:357)
10.04 09:26:42 [Server] INFO at io.github.xxyy.cmdblocker.lib.com.mcstats.Metrics.access$400(Metrics.java:64)
10.04 09:26:42 [Server] INFO at io.github.xxyy.cmdblocker.lib.com.mcstats.Metrics$1.run(Metrics.java:245)
10.04 09:26:42 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
10.04 09:26:42 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
10.04 09:26:42 [Server] INFO ... 3 more

**Comment by xxyy** [comment] 2016-04-10 13:49
That seems to be related to the plugin metrics. Does the plugin still work as expected?

**Comment by M9GLiquid** [comment] 2016-04-10 14:01
seems to be working but does it not have anything todo with the error before it?
"Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;"?

I'm just curious :)

**Comment by xxyy** [comment] 2016-04-10 14:02
That's actually the cause for the UnhandledException. Apparently, the version of Matrics included with the plugin has not been updated for "recent" API changes made in...1.7, I think? I'll look for a new version.

**Comment by M9GLiquid** [comment] 2016-04-10 14:03
Ohh alright, looking forward to a update then :)

**Comment by xxyy** [comment] 2016-04-10 14:05
Could you try [this](https://ci.nowak-at.net/job/public~cmdblkult/30/) development build and report if it still has the issue? I don't have a 1.9 server at hand for testing.

**Comment by M9GLiquid** [comment] 2016-04-10 14:07
will do give me a few secs here :)

**Comment by M9GLiquid** [comment] 2016-04-10 14:14
somehow this makes it so that it doesn't block anything. I might have done something wrong on my end i'll double check but that's the result as of yet

**Comment by xxyy** [comment] 2016-04-10 14:15
hm, weird. I'll set up a 1.9 server and test locally then.

**Comment by M9GLiquid** [comment] 2016-04-10 14:17
Here found the issue:

`10.04 10:16:02 [Server] ERROR Could not load 'plugins/CommandBlockerUltimate-1.3.5-SNAPSHOT.jar' in folder 'plugins'
10.04 10:16:02 [Server] INFO org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
10.04 10:16:02 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot52.jar:git-Spigot-1480adb-6247aa0]
10.04 10:16:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot52.jar:git-Spigot-1480adb-6247aa0]
10.04 10:16:02 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [spigot52.jar:git-Spigot-1480adb-6247aa0]
10.04 10:16:02 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [spigot52.jar:git-Spigot-1480adb-6247aa0]
10.04 10:16:02 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot52.jar:git-Spigot-1480adb-6247aa0]
10.04 10:16:02 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
10.04 10:16:02 [Server] INFO Caused by: java.util.zip.ZipException: zip file is empty
10.04 10:16:02 [Server] INFO at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_66]
10.04 10:16:02 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_66]
10.04 10:16:02 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_66]
10.04 10:16:02 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_66]
10.04 10:16:02 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_66]
10.04 10:16:02 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot52.jar:git-Spigot-1480adb-6247aa0]
10.04 10:16:02 [Server] INFO ... 5 more`

**Comment by xxyy** [comment] 2016-04-10 14:19
````
java.util.zip.ZipException: zip file is empty
````

Try redownloading the development build, myabe there was an error with your download.

**Comment by M9GLiquid** [comment] 2016-04-10 14:22
Yes that seemed to be the issue working fine now :) :+1:

**Comment by xxyy** [comment] 2016-04-10 14:27
Confirmed working. Release will be out shortly.

**Comment by xxyy** [comment] 2016-04-10 14:42
Released as 1.3.5, find more info [here](https://www.spigotmc.org/resources/command-blocker-ultimate.296/update?update=82726). Thanks for your help!

**Closed by xxyy** 2016-04-10 14:42 UTC
