### ISSUE TITLE
Compatibility issue by using Essentials

### ISSUE THREAD

**Issue by HeckiYT** [xxyy/commandblockerultimate#49] opened 2018-11-09 13:46 UTC
**Describe the bug**
I'm using Essentials and I blocked the command "/tell". Now my users can't run the "/msg" or "/m" comman.

**To Reproduce**
1. Install CBU and EssentialsX on your Server
2. Go to config of CBU and block the command "/tell"
3. Try to run "/msg" or "/m" as normal user without permissions or op.

**Expected behavior**
I wan't that the "/msg" and "/m" command isn't blocked while I blocked "/tell".
It only should be blocked if I write it in to my config.

**Offending plugin (please complete the following information):**
 - Plugin name and download link: 
   - EssentialsX
   - https://www.spigotmc.org/resources/essentialsx.9089/
 - Plugin version: 2.15.0.1
 - Configuration used: Isn't needed

**Environment (please complete the following information):**
 - Platform: Spigot
 - Platform version: http://prntscr.com/lgb5f3
 - CBU version http://prntscr.com/lgb5rz
 - Other relevant plugins: -

**Relevant server logs**
Aren't needed.

**Comment by xxyy** [comment] 2018-11-09 14:42
Thanks for your detailed report! What exactly are you trying to accomplish
with this? If you only want to block those literal commands (why?), you
have to disable alias resolution in the config file.

By default, CBU looks at what aliases are registered for a command so that
users cannot circumvent blocks by simply executing one of those. Note that
if you disable this, aliases won't be resolved for other commands either,
so you'll have to manually block those if desired.

If you're trying to block Minecraft's native /tell, simply block
/minecraft:tell instead.

**Comment by xxyy** [comment] 2018-11-09 14:51
Update, sorry, it can't do that yet! Duplicate of #29

**Comment by xxyy** [comment] 2019-01-01 19:58
Hey, sorry for the huge delay! I was very busy with uni and work. Anyways, please try this development build where you should be able to set `resolve-aliases` to `false` in `config.yml` in both Spigot and BungeeCord to stop alias resolution: https://ci.l1t.li/job/public~cmdblkult/94/

**Comment by xxyy** [comment] 2019-01-14 22:45
Are you still interested in this?

**Closed** 2019-01-14 22:45 UTC
