### ISSUE TITLE
Whitelist of commands instead of blacklist in "target-commands" section?

### ISSUE THREAD

**Issue by Chenguang1** [xxyy/commandblockerultimate#34] opened 2017-05-27 02:57 UTC
I would like to disable ALL the commands for my vanilla server. Is it possible to do with this plugin? And by ALL I mean all existing commands (like /help) and all not-existing commands or typos (like /fdsadfs) as well.

IF PLAYER TYPES SOMETHING (ANYTHING) AFTER SLASH HE SHOULD GET NO ERROR MESSAGE AT ALL

(both "show-error-message" and "show-tab-error-message" are false). No "unknown command" message, no "you don't have a permission" message, no nothing in respond.
Is it possible to create an empty whitelist of commands instead of creating a blacklist with many-many lines in "target-commands" section? Or if not through whitelist then through black list: block all the commands (known and unknown) that start with a,b,c,..,x,y,z letters and 0,1,2,..8,9 numbers?

**Comment by xxyy** [comment] 2017-05-27 17:57
This is not yet possible.

**Comment by Chenguang1** [comment] 2017-05-29 12:06
Okay. Thanks.

**Comment by xxyy** [comment] 2017-08-13 14:11
This is actually a duplicate of #27.

**Closed by xxyy** 2017-08-13 14:11 UTC
